import type { NextPage } from 'next';
import Head from 'next/head';
import { Header } from '../components/header/header';


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/f94f1e7176.js" crossOrigin="anonymous"></script>
      </Head>
      <Header />
    </>
  )
}

export default Home
