import Head from 'next/head';
import { ReactNode } from "react"
import { SHOP_NAME } from '../../GlobalVarible/global';
import { Footer } from "../footer/footer"
import { Header } from "../header/header"

type Layout = {
    children: ReactNode,
    title?: string
}

export const Layout = ({children, title = SHOP_NAME}: Layout) => {
    return (
        <>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script src="https://kit.fontawesome.com/f94f1e7176.js" crossOrigin="anonymous"></script>
        </Head>
        <Header />
            {children}
        <Footer />
        </>
    );
} 