import Head from 'next/head';
import { ReactNode } from "react"
import { Footer } from "../footer/footer"
import { Header } from "../header/header"

type Layout = {
    children: ReactNode
}

export const Layout = (props: Layout) => {
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script src="https://kit.fontawesome.com/f94f1e7176.js" crossOrigin="anonymous"></script>
        </Head>
        <Header />
            {props.children}
        <Footer />
        </>
    );
} 